[package]
name = "cache_cleaner"
version = "0.1.2"
authors = ["Dakota James Owen Keeler <Bearzrobotics@gmail.com>"]

[dependencies]
clap = "2.29"
log = "0.4"
simplelog = "0.4"


# Might use in the furture
#rust-ini = "0.10.0"
#ansi_term = "0.10.2"
#loggy = "0.1.7"

[[bin]]
name = "cache_cleaner"
path = "src/main.rs"