[package]
name = "cache_cleaner"
version = "0.1.2"
authors = ["Dakota James Owen Keeler <Bearzrobotics@gmail.com>"]

[dependencies]
clap = "2.29.0"
log = "0.4.0"


# Might use in the furture
#rust-ini = "0.10.0"
#ansi_term = "0.10.2"
